import requests
import json
import time

BASE_URL = "http://localhost:8000"

def test_ingest():
    print("Testing Ingestion...")
    try:
        response = requests.post(f"{BASE_URL}/ingest")
        response.raise_for_status()
        print("Ingestion Response:", json.dumps(response.json(), indent=2))
    except Exception as e:
        print(f"Ingestion Failed: {e}")
        if 'response' in locals():
            print("Error Details:", response.text)

def test_query(question):
    print(f"\nTesting Query: '{question}'")
    try:
        payload = {"query": question}
        start_time = time.time()
        response = requests.post(f"{BASE_URL}/query", json=payload)
        response.raise_for_status()
        duration = time.time() - start_time
        
        data = response.json()
        print(f"Time Taken: {duration:.2f}s")
        print("Answer:", data.get("answer"))
        
        return {
            "question": question,
            "answer": data.get("answer"),
            "citations": data.get("citations", []),
            "time": duration
        }
            
    except Exception as e:
        print(f"Query Failed: {e}")
        return {
            "question": question,
            "answer": f"Error: {str(e)}",
            "citations": [],
            "time": 0
        }

def generate_markdown_report(results):
    report_content = "# Evaluation Examples\n\nThis document records the responses generated by the system for the sample evaluation questions.\n\n"
    
    for i, res in enumerate(results, 1):
        if not res: continue
        
        report_content += f"## Question {i}\n"
        report_content += f"**Query:** \"{res['question']}\"\n\n"
        report_content += f"**System Response:**\n> {res.get('answer', 'No response')}\n\n"
        
        if res['citations']:
            report_content += "**Citations:**\n"
            for cite in res['citations']:
                report_content += f"- {cite.get('text_snippet', cite.get('source'))} (Page {cite.get('page')})\n"
        
        report_content += "\n**Review:**\n"
        report_content += "- [ ] Answer is grounded in dataset\n"
        report_content += "- [ ] Citation is present\n"
        report_content += "---\n\n"

    with open("EVALUATION_EXAMPLES.md", "w", encoding="utf-8") as f:
        f.write(report_content)
    print("\nSuccessfully generated EVALUATION_EXAMPLES.md")

if __name__ == "__main__":
    questions = [
        "What is Broken Access Control according to OWASP?",
        "What website security controls are required by the Thailand Web Security Standard?",
        "What is the difference between a Tactic and a Technique in MITRE ATT&CK?",
        "What mitigation steps does OWASP recommend for Injection vulnerabilities?",
        "How does MITRE describe the purpose of Persistence techniques?",
    ]
    
    # Optional: test_ingest()
    
    results = []
    for q in questions:
        res = test_query(q)
        results.append(res)
        
    generate_markdown_report(results)
